### ISSUE TITLE
Cannot deserialize some JSON strings

### ISSUE THREAD

**Issue by asonix** [hachyserve/rustypub#16]
consider this playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d265d1141acdeb0e7684ecc40d97e69

the `&'a str` type cannot be used to deserialize json strings containing `"`

Unfortunately, this will cost you in deserialization time since serde's behavior for Cow is to deserialize into the owned type: https://docs.rs/serde/latest/src/serde/de/impls.rs.html#1822-1834

**Comment by alexschrod** [comment]
> Unfortunately, this will cost you in deserialization time since serde's behavior for Cow is to deserialize into the owned type: https://docs.rs/serde/latest/src/serde/de/impls.rs.html#1822-1834

Yeah, you have to explicitly [tag `Cow` with a `#[serde(borrow)]` attribute to "borrow when possible."](https://serde.rs/lifetimes.html#borrowing-data-in-a-derived-impl)
